sudo: false
language: node_js
node_js:
  - "4.2"
addons:
  apt:
    packages:
      - socat
      - gcc-4.8
      - g++-4.8
env:
  - TARGET=test
  - TARGET=test-stress
  - TARGET=test-multi
  - TARGET=test-multi-remote
before_install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
  - echo . ~/.nvm/nvm.sh > ~/.bashrc.new
  - cat ~/.bashrc >> ~/.bashrc.new
  - mv ~/.bashrc.new ~/.bashrc
  - nvm alias default 4.2
  - ssh localhost node --version
script: npm run travis-$TARGET
