environment:
  matrix:
    - nodejs_version: "4"
      TARGET: test-win
    - nodejs_version: "4"
      TARGET: test-stress
    - nodejs_version: "4"
      TARGET: test-multi
    - nodejs_version: "6"
      TARGET: test-win
    - nodejs_version: "6"
      TARGET: test-stress
    - nodejs_version: "6"
      TARGET: test-multi
    - nodejs_version: "8"
      TARGET: test-win
    - nodejs_version: "8"
      TARGET: test-stress
    - nodejs_version: "8"
      TARGET: test-multi

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm install fs-ext
  - npm run ci-%TARGET%-%nodejs_version%

build: off
